### ISSUE TITLE
Crash when entity got killed by block

### ISSUE THREAD

**Issue by mercadanteus** [matcracker/BedcoreProtect#37] opened 2021-01-05 16:37 UTC
### Issue description

- Expected result: server don´t crash
- Actual result: Server crash

### Steps to reproduce the issue
I can´t figure what triggers the crash, only have logs

### OS and versions

* BedcoreProtect:  0.7.1

* PocketMine-MP:  3.17.2
* PHP: I'm using a host so I don't know this and the next answer
* Server OS:
* Game version: PE/Win10 (delete as appropriate)

### Plugins

Plugins (27): AntiBlock v1.0.0, ArmorStandExpanded v1.2.3, BedcoreProtect v0.7.1, BlockSniper v3.2.3, BuilderTools v1.2.0-beta2, ByteMe v1.0.0, ChestShop v2.4.0, ClearPlayer v1.0.0, CrashFixer v1, CustomAreas v1.2.1, EC-TableUI v1.1.2-pre, EconomyAPI v5.7.2, LiveXYZ v0.7.0, LockMyStuff v1.1.0, Netherite v1.1, OnlineTime v1.3, PiggyFactions v1.1.3, PlayerInfo v2.1.4, PureChat v1.4.11, PureEntitiesX v0.6.7, PurePerms v1.4.3, SimpleHome v1.0.3, Sponges v1.1.0, Uncensor v0.2.1, VanillaCoordinates v1.0.0, XGTAntiXRay v1.0.0, essentialsTP v1.2.2

- If you remove all plugins, does the issue still occur?  Error occurs one or two times a day so would take too much time to test it, and I have active players, if possible I would want to do not disturb them
- If the issue is **not** reproducible without plugins:
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

### Crashdump, backtrace or other files

https://pastebin.com/05QAShM4

https://pastebin.com/PGBBJwmf

**Comment by mercadanteus** [comment] 2021-01-05 22:25
Sorry above are the console logs, here is the crash dump: https://hastebin.com/zeholucuyi.yaml

**Comment by matcracker** [comment] 2021-01-23 15:00
I can't reproduce the crash, it was something related with the cactus

**Comment by mercadanteus** [comment] 2021-01-23 17:20
It began Working normally after some time, I´ll keep updated th thread if something new happens

**Comment by matcracker** [comment] 2021-05-07 15:42
I reproduced the crash, it happens when an entity got killed by a block. In your case was a cactus that killed someone. It will be fixed in v0.8.0.
Thanks for your report.

**Closed as completed** 2021-05-07 18:30 UTC
Labels: Resolution: Fixed
