### ISSUE TITLE
Problem shutting down plug-in when abnormal

### ISSUE THREAD

**Issue by cherrychip8293** [matcracker/BedcoreProtect#77] opened 2023-07-25 04:24 UTC
If the server fails and shuts down abnormally, the plug-in does not shut down when using the mysql connection, resulting in a bug in which the server is maintained

**Comment by matcracker** [comment] 2023-07-25 16:31
Hi, can you explain better your case? I tried to reproduce it but without any problem. Thank you.

**Comment by vkamz597** [comment] 2023-07-25 16:37
If you intentionally try to cause an error in a plug-in other than that plug-in, there will be a delay problem

**Comment by cherrychip8293** [comment] 2023-07-25 16:47
> Hi, can you explain better your case? I tried to reproduce it but without any problem. Thank you.

If you intentionally try to cause an error in a plug-in other than that plug-in, there will be a delay problem

**Comment by matcracker** [comment] 2023-07-25 17:01
> > Hi, can you explain better your case? I tried to reproduce it but without any problem. Thank you.
> 
> If you intentionally try to cause an error in a plug-in other than that plug-in, there will be a delay problem
> 
Ok, I'll try later.

**Comment by matcracker** [comment] 2023-07-25 20:57
I'm not able to reproduce the issue... Does it happen after a while the server is on?

**Comment by matcracker** [comment] 2023-07-25 21:30
Try to enable the debug-mode option in the config.yml of the plugin in order to see if something is printing during the shutdown.

**Comment by matcracker** [comment] 2023-07-26 20:27
Maybe it's related to https://github.com/poggit/libasynql/issues/85#issuecomment-1651751936

**Comment by matcracker** [comment] 2023-11-15 20:43
Fixed in v1.2.3

**Closed as completed by matcracker** 2023-11-15 20:43 UTC
Labels: Resolution: Cannot Reproduce
