### ISSUE TITLE
libasynql error not supporting PHP 8.1

### ISSUE THREAD

**Issue by SillierShark195** [matcracker/BedcoreProtect#66] opened 2023-05-18 15:40 UTC
PocketMine-MP Crash Dump Thu May 18 15:32:35 UTC 2023

PocketMine-MP version: 4.21.0 [Protocol 582]
Git commit: ef40934d24748025d15d9b86acc28fbb82d6de6a
PHP version: 8.1.19
OS: Linux, linux

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: BedcoreProtect

Error: During inheritance of JsonSerializable: Uncaught ErrorException: Return type of matcracker\BedcoreProtect\libs\poggit\libasynql\generic\GenericStatementImpl::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///home/container/plugins/BedcoreProtect (1).phar/src/matcracker/BedcoreProtect/libs/poggit/libasynql/generic/GenericStatementImpl.php:208
File: plugins/BedcoreProtect (1).phar/src/matcracker/BedcoreProtect/libs/poggit/libasynql/generic/GenericStatementImpl
Line: 41
Type: E_ERROR
Backtrace:

**Comment by matcracker** [comment] 2023-05-18 21:48
Hi, thanks for reporting. The issue is caused by an outdated library which triggers an error with PHP >= 8.1 which is required by PMMP 4.21.0.

The issue is already fixed in the PM5 branch, I need some time to make the same changes also on the PM4 version

**Comment by matcracker** [comment] 2023-05-18 22:00
The current workaround is to downgrade your PMMP version to 4.20.X

**Comment by SillierShark195** [comment] 2023-05-19 01:19
> The current workaround is to downgrade your PMMP version to 4.20.X

Is fine ill waiting until is fixed

**Closed as completed** 2023-05-25 20:22 UTC
Labels: Resolution: Fixed
